# Generated by Django 5.1.4 on 2025-01-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_skill_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='body',
        ),
    ]
