# Generated by Django 5.1.4 on 2025-01-09 05:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_description_skill_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e1b0b949-c333-4caf-b769-80a6665a7ae4'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
