# Generated by Django 5.1.4 on 2025-01-09 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.UUIDField(default=uuid.UUID('854cd87d-78b2-4cd1-a6ef-591e11441b3b'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
