# Generated by Django 5.1.4 on 2025-01-12 06:05

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='body',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
